In [3]:
import numpy as np

In [128]:
#1 +
def arr_replace(x):
    x = np.array(x)
    x[x % 2 != 0] = 0
    return x

arr_replace([1,2,3,4,5])

array([0, 2, 0, 4, 0])

In [143]:
#2+
def arr_replace_where(x):
    x = np.array(x)
    return np.where(x % 2 != 0, x, 0)

arr_replace_where([1,2,3,4,5,6])
    

array([1, 0, 3, 0, 5, 0])

In [100]:
#3 +
def arr_repeat(x):
    return np.repeat(x,3)

arr_repeat([1,2,3])
    

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [5]:
#4
def arr_join(x):
    return np.tile(x,2)

arr_join([1,2,3])

array([1, 2, 3, 1, 2, 3])

In [101]:
#4 +
def arr_join_2(x):
    return np.concatenate((x,x,x))

arr_join_2([1,2,3])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [3]:
#5+
def arr_intersection(x,y):
    return np.intersect1d(x,y)

arr_intersection(np.array([1,2,3]),np.array([3,2,1]))

array([1, 2, 3])

In [56]:
#6+
def arr_random(x,y):
    return np.random.uniform(5,10, size = (x,y))

arr_random(2,2)

array([[8.40690971, 8.59407695],
       [5.72871733, 7.62034852]])